name: nebula_expense
description: "Nebula Expense - Advanced Military-Grade Offline Expense Tracker with Quantum-Resistant Security"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.7
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core UI and Navigation
  cupertino_icons: ^1.0.8
  go_router: ^13.2.4
  flutter_riverpod: ^2.5.1
  
  # Local Storage and Encryption
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  
  # Security and Authentication
  local_auth: ^2.1.8
  flutter_secure_storage: ^9.0.0
  
  # File Handling and Attachments
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  
  # Charts and Visualizations
  fl_chart: ^0.66.2
  
  # Utilities
  uuid: ^4.2.1
  json_annotation: ^4.8.1
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  
  # Import/Export
  csv: ^5.1.1
  archive: ^3.4.10
  
  # Theme and UI
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  
  # Testing
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/data/
    - assets/themes/
